# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bibliotheque.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WizardPage(object):
    def setupUi(self, WizardPage):
        WizardPage.setObjectName("WizardPage")
        WizardPage.resize(990, 729)
        self.label = QtWidgets.QLabel(WizardPage)
        self.label.setGeometry(QtCore.QRect(150, 70, 131, 51))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(WizardPage)
        self.label_2.setGeometry(QtCore.QRect(150, 110, 131, 51))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(WizardPage)
        self.label_3.setGeometry(QtCore.QRect(150, 270, 221, 51))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(WizardPage)
        self.label_4.setGeometry(QtCore.QRect(150, 230, 231, 51))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(WizardPage)
        self.label_5.setGeometry(QtCore.QRect(150, 190, 201, 51))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(WizardPage)
        self.label_6.setGeometry(QtCore.QRect(150, 150, 141, 51))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(WizardPage)
        self.label_7.setGeometry(QtCore.QRect(180, 20, 231, 16))
        self.label_7.setObjectName("label_7")
        self.tableView = QtWidgets.QTableView(WizardPage)
        self.tableView.setGeometry(QtCore.QRect(480, 70, 481, 231))
        self.tableView.setObjectName("tableView")
        self.verticalLayoutWidget = QtWidgets.QWidget(WizardPage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(130, 360, 711, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(WizardPage)
        self.pushButton.setGeometry(QtCore.QRect(750, 460, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.label_9 = QtWidgets.QLabel(WizardPage)
        self.label_9.setGeometry(QtCore.QRect(40, 60, 55, 16))
        self.label_9.setObjectName("label_9")
        self.lineEdit = QtWidgets.QLineEdit(WizardPage)
        self.lineEdit.setGeometry(QtCore.QRect(140, 460, 381, 111))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(WizardPage)
        QtCore.QMetaObject.connectSlotsByName(WizardPage)

    def retranslateUi(self, WizardPage):
        _translate = QtCore.QCoreApplication.translate
        WizardPage.setWindowTitle(_translate("WizardPage", "WizardPage"))
        self.label.setText(_translate("WizardPage", "1. AJOUTER UN LIVRE"))
        self.label_2.setText(_translate("WizardPage", "2. EMPRUNTER UN LIVRE"))
        self.label_3.setText(_translate("WizardPage", "7. AJOUTER UN EMPRUNTEUR"))
        self.label_4.setText(_translate("WizardPage", "5. AFFICHER LA LISTE DES EMPRUNTERS"))
        self.label_5.setText(_translate("WizardPage", "4. AFFICHER LA LISTE DES LIVRES"))
        self.label_6.setText(_translate("WizardPage", "3. RENDRE UN LIVRE"))
        self.label_7.setText(_translate("WizardPage", "PLATEFORME DE LA BIBLIOTHEQUE"))
        self.pushButton.setText(_translate("WizardPage", "OK"))
        self.label_9.setText(_translate("WizardPage", "MENU"))
